Rebol [
    system: "Rebol [R3] Language Interpreter and Run-time Environment"
    title: "REBOL 3 Boot Base: Constants and Equates"
    rights: {
        Copyright 2012 REBOL Technologies
        REBOL is a trademark of REBOL Technologies
    }
    license: {
        Licensed under the Apache License, Version 2.0
        See: http://www.apache.org/licenses/LICENSE-2.0
    }
    notes: {
        This code is evaluated just after actions, natives, sysobj, and other lower
        levels definitions. This file intializes a minimal working environment
        that is used for the rest of the boot.
    }
]

; NOTE: The system is not fully booted at this point, so only simple
; expressions are allowed. Anything else will crash the boot.

;-- Standard constants:
zero: 0

;-- Special values:
REBOL: system
sys: system
sys/util: system/contexts/sys
lib: system/contexts/lib

;-- Char constants:
NUL:       #"^(NULL)"
space:     #" "
SP:        space
backspace: #"^(BACK)"
BS:        backspace
tab:       #"^-"
newline:   #"^/"
newpage:   #"^l"
slash:     #"/"
backslash: #"\"
escape:    #"^(ESC)"
CR:        #"^M"
LF:        newline

;-- Function synonyms:
to-logic: :did?
min: :minimum
max: :maximum
abs: :absolute

; Words for BLANK! and bar, for those who don't like symbols

blank: _
bar: '|

; !!! There could be a datatype which evaluated to a null, but there can't
; be a literal type that *is* null.  Currently it's generated by a native.

~: func [
    "Function returning trash result"
    return: [~]
][
    ;-- Note: actually *faster* than a native, due to Void_Dispatcher()
]
