; datatypes/datatype.r
(not datatype? 1)
(datatype! = type of action!)
(datatype? action!)
(datatype? blob!)
(datatype? bitset!)
(datatype? block!)
(datatype? char!)
(datatype? datatype!)
(datatype? date!)
(datatype? decimal!)
(datatype? email!)
(datatype? error!)
(datatype? event!)
(datatype? file!)
(datatype? get-path!)
(datatype? get-word!)
(datatype? handle!)
(datatype? integer!)
(datatype? issue!)
(datatype? lit-path!)
(datatype? lit-word!)
(typeset? logic!)
(datatype? map!)
(datatype? module!)
(datatype? money!)
(datatype? blank!)
(datatype? object!)
(datatype? pair!)
(datatype? group!)
(datatype? path!)
(datatype? percent!)
(datatype? port!)
(datatype? refinement!)
(datatype? set-path!)
(datatype? set-word!)
(datatype? text!)
(datatype? tag!)
(datatype? time!)
(datatype? tuple!)
(datatype? typeset!)
(datatype? url!)
(datatype? word!)
; alternative literal representation
(datatype? #[datatype! action!])
