; datatypes/datatype.r
(not type-word? 1)
(type-word! = kind of frame!)
(type-word? frame!)
(type-word? binary!)
(type-word? bitset!)
(type-word? block!)
(type-word? type-word!)
(type-word? date!)
(type-word? decimal!)
(type-word? email!)
(type-word? error!)
(type-word? file!)
(type-word? get-path!)  ; get-path! =? path! in R2/Forward, R2 2.7.7+
(type-word? get-word!)
(type-word? handle!)
(type-word? integer!)
(type-word? issue!)
(type-word? map!)  ; map! =? hash! in R2/Forward, R2 2.7.7+
(type-word? module!)
(type-word? money!)
(type-word? blank!)
(type-word? object!)
(type-word? pair!)
(type-word? group!)
(type-word? path!)
(type-word? percent!)
(type-word? port!)
(type-word? set-path!)
(type-word? set-word!)
(type-word? text!)
(type-word? tag!)
(type-word? time!)
(type-word? tuple!)
(type-word? parameter!)
(type-word? url!)
(type-word? word!)

; literal representation
(type-word? &frame!)

; Now a type constraint, not a datatype
(type-group? logic?!)
