language: c
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "IsBMCZ1i6H6dfqhijrv9ONGa/trg/rzH+ajm+rlrQeoQhGpKeICECX+jl+HIJsfqdcRe875WeWKggFJ+WwArAROioAeSoUn0md/hnJ92EqLaomszTPAUOmseP2Uq2f+dDDl45Yy9mAud0OH6lprlOh/i5t2gwkHP7r+71hjz0K4="

install:
    - sudo apt-get install realpath
    - sudo apt-get install texinfo
    - sudo apt-get install libgtk-3-dev

branches:
    only:
        coverity_scan

addons:
  coverity_scan:
    project:
      name: "zsx/r3"
      description: "Build submitted via Travis CI"
    notification_email: zeng.shixin@gmail.com
    build_command_prepend: ""
    build_command:   "bash make/scripts/build.sh linux-64"
    branch_pattern: coverity_scan

script: true
