; Rebol []
; *****************************************************************************
; Title: Rebol core tests
; Copyright:
;     2012 REBOL Technologies
;     2013 Saphirion AG
; Author:
;     Carl Sassenrath, Ladislav Mecir, Andreas Bolka, Brian Hawley, John K
; License:
;     Licensed under the Apache License, Version 2.0 (the "License");
;     you may not use this file except in compliance with the License.
;     You may obtain a copy of the License at
;
;     http://www.apache.org/licenses/LICENSE-2.0
;
;     Unless required by applicable law or agreed to in writing, software
;     distributed under the License is distributed on an "AS IS" BASIS,
;     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
;     See the License for the specific language governing permissions and
;     limitations under the License.
; *****************************************************************************
%parse-tests.r

%core/datatypes/action.test.reb
%core/datatypes/binary.test.reb
%core/datatypes/bitset.test.reb
%core/datatypes/block.test.reb
%core/datatypes/char.test.reb
%core/datatypes/closure.test.reb
%core/datatypes/datatype.test.reb
%core/datatypes/date.test.reb
%core/datatypes/decimal.test.reb
%core/datatypes/email.test.reb
%core/datatypes/error.test.reb
%core/datatypes/event.test.reb
%core/datatypes/file.test.reb
%core/datatypes/function.test.reb
%core/datatypes/get-path.test.reb
%core/datatypes/get-word.test.reb
%core/datatypes/gob.test.reb
%core/datatypes/hash.test.reb
%core/datatypes/image.test.reb
%core/datatypes/integer.test.reb
%core/datatypes/issue.test.reb
%core/datatypes/list.test.reb
%core/datatypes/lit-path.test.reb
%core/datatypes/lit-word.test.reb
%core/datatypes/logic.test.reb
%core/datatypes/map.test.reb
%core/datatypes/module.test.reb
%core/datatypes/money.test.reb
%core/datatypes/native.test.reb
%core/datatypes/none.test.reb
%core/datatypes/object.test.reb
%core/datatypes/op.test.reb
%core/datatypes/pair.test.reb
%core/datatypes/paren.test.reb
%core/datatypes/path.test.reb
%core/datatypes/percent.test.reb
%core/datatypes/port.test.reb
%core/datatypes/refinement.test.reb
%core/datatypes/set-path.test.reb
%core/datatypes/set-word.test.reb
%core/datatypes/string.test.reb
%core/datatypes/symbol.test.reb
%core/datatypes/time.test.reb
%core/datatypes/tuple.test.reb
%core/datatypes/typeset.test.reb
%core/datatypes/unset.test.reb
%core/datatypes/url.test.reb
%core/datatypes/vector.test.reb
%core/datatypes/word.test.reb
%core/comparison/lesserq.test.reb
%core/comparison/maximum-of.test.reb
%core/comparison/equalq.test.reb
%core/comparison/equivq.test.reb
%core/comparison/sameq.test.reb
%core/comparison/strict-equalq.test.reb
%core/comparison/strict-not-equalq.test.reb
%core/context/bind.test.reb
%core/context/boundq.test.reb
%core/context/bindq.test.reb
%core/context/resolve.test.reb
%core/context/set.test.reb
%core/context/unset.test.reb
%core/context/use.test.reb
%core/context/valueq.test.reb
%core/control/all.test.reb
%core/control/any.test.reb
%core/control/apply.test.reb
%core/control/attempt.test.reb
%core/control/break.test.reb
%core/control/case.test.reb
%core/control/catch.test.reb
%core/control/compose.test.reb
%core/control/continue.test.reb
%core/control/disarm.test.reb
%core/control/do.test.reb
%core/control/either.test.reb
%core/control/else.test.reb
%core/control/exit.test.reb
%core/control/for.test.reb
%core/control/forall.test.reb
%core/control/for-each.test.reb
%core/control/forever.test.reb
%core/control/forskip.test.reb
%core/control/halt.test.reb
%core/control/if.test.reb
%core/control/loop.test.reb
%core/control/map-each.test.reb
%core/control/reduce.test.reb
%core/control/remove-each.test.reb
%core/control/repeat.test.reb
%core/control/return.test.reb
%core/control/switch.test.reb
%core/control/throw.test.reb
%core/control/try.test.reb
%core/control/unless.test.reb
%core/control/until.test.reb
%core/control/wait.test.reb
%core/control/while.test.reb
%core/control/quit.test.reb
%core/convert/as-binary.test.reb
%core/convert/as-string.test.reb
%core/convert/encode.test.reb
%core/convert/load.test.reb
%core/convert/mold.test.reb
%core/convert/to.test.reb
%core/datatype/as-pair.test.reb
%core/define/func.test.reb
%core/convert/to-hex.test.reb
%core/file/clean-path.test.reb
%core/file/existsq.test.reb
%core/file/make-dir.test.reb
%core/file/open.test.reb
%core/file/file-typeq.test.reb
%core/math/absolute.test.reb
%core/math/add.test.reb
%core/math/and.test.reb
%core/math/arcsine.test.reb
%core/math/arctangent.test.reb
%core/math/complement.test.reb
%core/math/cosine.test.reb
%core/math/difference.test.reb
%core/math/divide.test.reb
%core/math/evenq.test.reb
%core/math/exp.test.reb
%core/math/log-10.test.reb
%core/math/log-2.test.reb
%core/math/log-e.test.reb
%core/math/mod.test.reb
%core/math/modulo.test.reb
%core/math/multiply.test.reb
%core/math/negate.test.reb
%core/math/negativeq.test.reb
%core/math/not.test.reb
%core/math/oddq.test.reb
%core/math/positiveq.test.reb
%core/math/power.test.reb
%core/math/random.test.reb
%core/math/remainder.test.reb
%core/math/round.test.reb
%core/math/shift.test.reb
%core/math/signq.test.reb
%core/math/sine.test.reb
%core/math/square-root.test.reb
%core/math/subtract.test.reb
%core/math/tangent.test.reb
%core/math/zeroq.test.reb
%core/reflectors/body-of.test.reb
%core/secure/protect.test.reb
%core/secure/unprotect.test.reb
%core/series/append.test.reb
%core/series/at.test.reb
%core/series/back.test.reb
%core/series/change.test.reb
%core/series/clear.test.reb
%core/series/copy.test.reb
%core/series/difference.test.reb
%core/series/emptyq.test.reb
%core/series/exclude.test.reb
%core/series/find.test.reb
%core/series/indexq.test.reb
%core/series/insert.test.reb
%core/series/intersect.test.reb
%core/series/last.test.reb
%core/series/lengthq.test.reb
%core/series/next.test.reb
%core/series/ordinals.test.reb
%core/series/pick.test.reb
%core/series/poke.test.reb
%core/series/remove.test.reb
%core/series/reverse.test.reb
%core/series/select.test.reb
%core/series/skip.test.reb
%core/series/sort.test.reb
%core/series/split.test.reb
%core/series/tailq.test.reb
%core/series/trim.test.reb
%core/series/union.test.reb
%core/string/checksum.test.reb
%core/string/compress.test.reb
%core/string/decloak.test.reb
%core/string/decode.test.reb
%core/string/encode.test.reb
%core/string/decompress.test.reb
%core/string/dehex.test.reb
%core/system/system.test.reb
%core/system/file.test.reb
%core/system/gc.test.reb
%core/source/analysis.test.reb
