REBOL [
    date: 8-Jul-2016/12:38:08+10:00
    comment: "test-editor/mapping"
]
%core/datatypes/action.test.reb datatypes/action.r
%core/datatypes/binary.test.reb datatypes/binary.r
%core/datatypes/bitset.test.reb datatypes/bitset.r
%core/datatypes/block.test.reb datatypes/block.r
%core/datatypes/char.test.reb datatypes/char.r
%core/datatypes/closure.test.reb datatypes/closure.r
%core/datatypes/datatype.test.reb datatypes/datatype.r
%core/datatypes/date.test.reb datatypes/date.r
%core/datatypes/decimal.test.reb datatypes/decimal.r
%core/datatypes/email.test.reb datatypes/email.r
%core/datatypes/error.test.reb datatypes/error.r
%core/datatypes/event.test.reb datatypes/event.r
%core/datatypes/file.test.reb datatypes/file.r
%core/datatypes/function.test.reb datatypes/function.r
%core/datatypes/get-path.test.reb datatypes/get-path.r
%core/datatypes/get-word.test.reb datatypes/get-word.r
%core/datatypes/gob.test.reb datatypes/gob.r
%core/datatypes/hash.test.reb datatypes/hash.r
%core/datatypes/image.test.reb datatypes/image.r
%core/datatypes/integer.test.reb datatypes/integer.r
%core/datatypes/issue.test.reb datatypes/issue.r
%core/datatypes/list.test.reb datatypes/list.r
%core/datatypes/lit-path.test.reb datatypes/lit-path.r
%core/datatypes/lit-word.test.reb datatypes/lit-word.r
%core/datatypes/logic.test.reb datatypes/logic.r
%core/datatypes/map.test.reb datatypes/map.r
%core/datatypes/module.test.reb datatypes/module.r
%core/datatypes/money.test.reb datatypes/money.r
%core/datatypes/native.test.reb datatypes/native.r
%core/datatypes/none.test.reb datatypes/none.r
%core/datatypes/object.test.reb datatypes/object.r
%core/datatypes/op.test.reb datatypes/op.r
%core/datatypes/pair.test.reb datatypes/pair.r
%core/datatypes/paren.test.reb datatypes/paren.r
%core/datatypes/path.test.reb datatypes/path.r
%core/datatypes/percent.test.reb datatypes/percent.r
%core/datatypes/port.test.reb datatypes/port.r
%core/datatypes/refinement.test.reb datatypes/refinement.r
%core/datatypes/set-path.test.reb datatypes/set-path.r
%core/datatypes/set-word.test.reb datatypes/set-word.r
%core/datatypes/string.test.reb datatypes/string.r
%core/datatypes/symbol.test.reb datatypes/symbol.r
%core/datatypes/time.test.reb datatypes/time.r
%core/datatypes/tuple.test.reb datatypes/tuple.r
%core/datatypes/typeset.test.reb datatypes/typeset.r
%core/datatypes/unset.test.reb datatypes/unset.r
%core/datatypes/url.test.reb datatypes/url.r
%core/datatypes/vector.test.reb datatypes/vector.r
%core/datatypes/word.test.reb datatypes/word.r
%core/comparison/lesserq.test.reb functions/comparison/lesserq.r
%core/comparison/maximum-of.test.reb functions/comparison/maximum-of.r
%core/comparison/equalq.test.reb functions/comparison/equalq.r
%core/comparison/equivq.test.reb functions/comparison/equivq.r
%core/comparison/sameq.test.reb functions/comparison/sameq.r
%core/comparison/strict-equalq.test.reb functions/comparison/strict-equalq.r
%core/comparison/strict-not-equalq.test.reb functions/comparison/strict-not-equalq.r
%core/context/bind.test.reb functions/context/bind.r
%core/context/boundq.test.reb functions/context/boundq.r
%core/context/bindq.test.reb functions/context/bindq.r
%core/context/resolve.test.reb functions/context/resolve.r
%core/context/set.test.reb functions/context/set.r
%core/context/unset.test.reb functions/context/unset.r
%core/context/use.test.reb functions/context/use.r
%core/context/valueq.test.reb functions/context/valueq.r
%core/control/all.test.reb functions/control/all.r
%core/control/any.test.reb functions/control/any.r
%core/control/apply.test.reb functions/control/apply.r
%core/control/attempt.test.reb functions/control/attempt.r
%core/control/break.test.reb functions/control/break.r
%core/control/case.test.reb functions/control/case.r
%core/control/catch.test.reb functions/control/catch.r
%core/control/compose.test.reb functions/control/compose.r
%core/control/continue.test.reb functions/control/continue.r
%core/control/disarm.test.reb functions/control/disarm.r
%core/control/do.test.reb functions/control/do.r
%core/control/either.test.reb functions/control/either.r
%core/control/else.test.reb functions/control/else.r
%core/control/exit.test.reb functions/control/exit.r
%core/control/for.test.reb functions/control/for.r
%core/control/forall.test.reb functions/control/forall.r
%core/control/for-each.test.reb functions/control/for-each.r
%core/control/forever.test.reb functions/control/forever.r
%core/control/forskip.test.reb functions/control/forskip.r
%core/control/halt.test.reb functions/control/halt.r
%core/control/if.test.reb functions/control/if.r
%core/control/loop.test.reb functions/control/loop.r
%core/control/map-each.test.reb functions/control/map-each.r
%core/control/reduce.test.reb functions/control/reduce.r
%core/control/remove-each.test.reb functions/control/remove-each.r
%core/control/repeat.test.reb functions/control/repeat.r
%core/control/return.test.reb functions/control/return.r
%core/control/switch.test.reb functions/control/switch.r
%core/control/throw.test.reb functions/control/throw.r
%core/control/try.test.reb functions/control/try.r
%core/control/unless.test.reb functions/control/unless.r
%core/control/until.test.reb functions/control/until.r
%core/control/wait.test.reb functions/control/wait.r
%core/control/while.test.reb functions/control/while.r
%core/control/quit.test.reb functions/control/quit.r
%core/convert/as-binary.test.reb functions/convert/as-binary.r
%core/convert/as-string.test.reb functions/convert/as-string.r
%core/convert/encode.test.reb functions/convert/encode.r
%core/convert/load.test.reb functions/convert/load.r
%core/convert/mold.test.reb functions/convert/mold.r
%core/convert/to.test.reb functions/convert/to.r
%core/datatype/as-pair.test.reb functions/datatype/as-pair.r
%core/define/func.test.reb functions/define/func.r
%core/convert/to-hex.test.reb functions/convert/to-hex.r
%core/file/clean-path.test.reb functions/file/clean-path.r
%core/file/existsq.test.reb functions/file/existsq.r
%core/file/make-dir.test.reb functions/file/make-dir.r
%core/file/open.test.reb functions/file/open.r
%core/file/file-typeq.test.reb functions/file/file-typeq.r
%core/math/absolute.test.reb functions/math/absolute.r
%core/math/add.test.reb functions/math/add.r
%core/math/and.test.reb functions/math/and.r
%core/math/arcsine.test.reb functions/math/arcsine.r
%core/math/arctangent.test.reb functions/math/arctangent.r
%core/math/complement.test.reb functions/math/complement.r
%core/math/cosine.test.reb functions/math/cosine.r
%core/math/difference.test.reb functions/math/difference.r
%core/math/divide.test.reb functions/math/divide.r
%core/math/evenq.test.reb functions/math/evenq.r
%core/math/exp.test.reb functions/math/exp.r
%core/math/log-10.test.reb functions/math/log-10.r
%core/math/log-2.test.reb functions/math/log-2.r
%core/math/log-e.test.reb functions/math/log-e.r
%core/math/mod.test.reb functions/math/mod.r
%core/math/modulo.test.reb functions/math/modulo.r
%core/math/multiply.test.reb functions/math/multiply.r
%core/math/negate.test.reb functions/math/negate.r
%core/math/negativeq.test.reb functions/math/negativeq.r
%core/math/not.test.reb functions/math/not.r
%core/math/oddq.test.reb functions/math/oddq.r
%core/math/positiveq.test.reb functions/math/positiveq.r
%core/math/power.test.reb functions/math/power.r
%core/math/random.test.reb functions/math/random.r
%core/math/remainder.test.reb functions/math/remainder.r
%core/math/round.test.reb functions/math/round.r
%core/math/shift.test.reb functions/math/shift.r
%core/math/signq.test.reb functions/math/signq.r
%core/math/sine.test.reb functions/math/sine.r
%core/math/square-root.test.reb functions/math/square-root.r
%core/math/subtract.test.reb functions/math/subtract.r
%core/math/tangent.test.reb functions/math/tangent.r
%core/math/zeroq.test.reb functions/math/zeroq.r
%core/reflectors/body-of.test.reb functions/reflectors/body-of.r
%core/secure/protect.test.reb functions/secure/protect.r
%core/secure/unprotect.test.reb functions/secure/unprotect.r
%core/series/append.test.reb functions/series/append.r
%core/series/at.test.reb functions/series/at.r
%core/series/back.test.reb functions/series/back.r
%core/series/change.test.reb functions/series/change.r
%core/series/clear.test.reb functions/series/clear.r
%core/series/copy.test.reb functions/series/copy.r
%core/series/difference.test.reb functions/series/difference.r
%core/series/emptyq.test.reb functions/series/emptyq.r
%core/series/exclude.test.reb functions/series/exclude.r
%core/series/find.test.reb functions/series/find.r
%core/series/indexq.test.reb functions/series/indexq.r
%core/series/insert.test.reb functions/series/insert.r
%core/series/intersect.test.reb functions/series/intersect.r
%core/series/last.test.reb functions/series/last.r
%core/series/lengthq.test.reb functions/series/lengthq.r
%core/series/next.test.reb functions/series/next.r
%core/series/ordinals.test.reb functions/series/ordinals.r
%core/series/pick.test.reb functions/series/pick.r
%core/series/poke.test.reb functions/series/poke.r
%core/series/remove.test.reb functions/series/remove.r
%core/series/reverse.test.reb functions/series/reverse.r
%core/series/select.test.reb functions/series/select.r
%core/series/skip.test.reb functions/series/skip.r
%core/series/sort.test.reb functions/series/sort.r
%core/series/split.test.reb functions/series/split.r
%core/series/tailq.test.reb functions/series/tailq.r
%core/series/trim.test.reb functions/series/trim.r
%core/series/union.test.reb functions/series/union.r
%core/string/checksum.test.reb functions/string/checksum.r
%core/string/compress.test.reb functions/string/compress.r
%core/string/decloak.test.reb functions/string/decloak.r
%core/string/decode.test.reb functions/string/decode.r
%core/string/encode.test.reb functions/string/encode.r
%core/string/decompress.test.reb functions/string/decompress.r
%core/string/dehex.test.reb functions/string/dehex.r
%core/system/system.test.reb system/system.r
%core/system/file.test.reb system/file.r
%core/system/gc.test.reb system/gc.r
%core/source/analysis.test.reb source/analysis.r
