//
//  file: %enum-types.h
//  summary: -[Safe wrapper for distinguishing "Heart" and "Type" if C++]-
//  project: "Rebol 3 Interpreter and Run-time (Ren-C branch)"
//  homepage: https://github.com/metaeducation/ren-c/
//
//=////////////////////////////////////////////////////////////////////////=//
//
// Copyright 2012 REBOL Technologies
// Copyright 2012-2026 Ren-C Open Source Contributors
// REBOL is a trademark of REBOL Technologies
//
// See README.md and CREDITS.md for more information
//
// Licensed under the Lesser GPL, Version 3.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.gnu.org/licenses/lgpl-3.0.html
//
//=////////////////////////////////////////////////////////////////////////=//
//
// There is a basic idea in the system that tests like Is_Word() or WORD? do
// not consider quoted words (or quasi-words, or anti-words) to be "Word".
// They may have a cell layout and payload that carries a symbol and a binding
// like a word, but should not be confused with them.
//
// This distinction has led to a difference in considering the "Type_Of()" of
// a cell in comparison with the "Heart_Of()".  If you ask a word at any
// quoting level what the heart of the cell is, it will say TYPE_WORD.  But
// only a word at the zero quoting level will respond with TYPE_WORD to
// Type_Of().  Otherwise it can give other answers (like TYPE_QUASIFORM, or
// TYPE_LOGIC, or some TYPE_QUOTED_4_TIMES_NONQUASI weirdo answer.)
//
// This means that the extra "types" generated by quoting states are not
// "cell hearts" describing their layout, but a sort of "pseudotype".  It
// would be incorrect to put these values into a cell's heart, and it's also
// make-work to check for them when you're sure you're dealing with something
// that is constrained to being a valid cell heart.
//
// Hence, only HEART_XXX values can be written into HEARTSIGIL_BYTE():
//
//    HEARTSIGIL_BYTE(cell) = HEART_INTEGER;  // valid
//    HEARTSIGIL_BYTE(cell) = TYPE_QUASIFORM;  // invalid, it's a pseudotype
//
// And you shouldn't really be comparing Heart against pseudotypes:
//
//    void Some_Function(Heart heart) {
//       if (heart == TYPE_QUASIFORM)  // invalid, it's a pseudotype
//         { ... }
//    }
//
// 1. All extension types use the 0 byte for their heart.  This means that
//    you can't say (Heart_Of(cell1) == Heart_Of(cell2)) and get a correct
//    answer in the case of extension types.  To avoid that problem, we
//    have Heart_Of() return an Optional(Type), which we then prohibit the
//    comparison of Option(Heart) to Option(Heart).  You can still compare an
//    unwrapped Heart to an Option(Heart).
//

typedef Byte HeartByte;  // value is >= MIN_TYPE_HEART, <= MAX_TYPE_HEART

#if (! DEBUG_EXTRA_HEART_CHECKS)
    typedef HeartEnum Heart;
    typedef TypeEnum Type;
#else
    struct Type {  // v-- an "enum class" in MSVC (members are TypeEnum::XXX)
        NEEDFUL_DECLARE_WRAPPED_FIELD(TypeEnum, t);

        Type () = default;
        Type (TypeEnum type) : t (type) {}

        // !!! needed for u_cast(Option(Type), Byte) -- review ideas
        explicit Type (uintptr_t u) : t (i_cast(TypeEnum, u)) {}

        Type (needful::Nocast0Struct)  // for return fail with Result(Type)
          : t (i_cast(TypeEnum, 0))  // (also used by Option(Type) = none)
        {}

        explicit operator bool() const  // for Option(Type) in if() statements
          { return t != i_cast(TypeEnum, 0); }

        explicit operator uintptr_t() const
          { return i_cast(uintptr_t, t); }

        operator TypeEnum() const
          { return t; }
    };

    // Types cannot be directly compared against each other, because there
    // are a lot of states that represent "TYPE_QUOTED".  We don't want to
    // pay to collapse those states to a canon value on every Type_Of() call,
    // so it's better to disable the comparison and have an Is_Quoted_Type()
    // function as well as a Same_Types() if you want the expensive check.
    //
    // (LOGIC! is also not canonized, but split into OKAY and NULL states)

    INLINE bool operator==(Type& left, Type& right) = delete;
    INLINE bool operator!=(Type& left, Type& right) = delete;

    // While Type wrapper classes can't be compared to each other, we allow
    // them to be compared directly with TYPE_XXX values.  (We need to use
    // ENABLE_IF_EXACT_ARG_TYPE() to avoid the automatic conversion of Type
    // to TypeEnum becoming a back door to doing Type-to-Type comparisons.)

    ENABLE_IF_EXACT_ARG_TYPE(TypeEnum)
    INLINE bool operator>=(Type& type, T&& t)
      { return type.t >= t; }

    ENABLE_IF_EXACT_ARG_TYPE(TypeEnum)
    INLINE bool operator>=(T&& t, Type& type)
      { return t >= type.t; }

    ENABLE_IF_EXACT_ARG_TYPE(TypeEnum)
    INLINE bool operator<=(Type& type, T&& t)
      { return type.t <= t; }

    ENABLE_IF_EXACT_ARG_TYPE(TypeEnum)
    INLINE bool operator<=(T&& t, Type& type)
      { return t <= type.t; }

    ENABLE_IF_EXACT_ARG_TYPE(TypeEnum)
    INLINE bool operator>(Type& type, T&& t)
      { return type.t > t; }

    ENABLE_IF_EXACT_ARG_TYPE(TypeEnum)
    INLINE bool operator>(T&& t, Type& type)
      { return t > type.t; }

    ENABLE_IF_EXACT_ARG_TYPE(TypeEnum)
    INLINE bool operator<(Type& type, T&& t)
      { return type.t < t; }

    ENABLE_IF_EXACT_ARG_TYPE(TypeEnum)
    INLINE bool operator<(T&& t, Type& type)
      { return t < type.t; }

    typedef HeartEnum Heart;
#endif


INLINE bool Is_Quoted_Type(Option(Type) type) {
    if (ii_cast(TypeEnum, type) <= MAX_TYPE_NOQUOTE_QUASI_OK)
        return false;
    if (ii_cast(TypeEnum, type) > MAX_TYPE_ELEMENT)
        return false;
    return true;
}

INLINE bool Is_Logic_Type(Option(Type) type) {
    return (
        ii_cast(TypeEnum, type) == TYPE_LOGIC_NULL
        or ii_cast(TypeEnum, type) == TYPE_LOGIC_OKAY
    );
}

#define Is_Logic(v) \
    Is_Logic_Type(Type_Of(v))


//=//// CUSTOM DATATYPE HEART (0) /////////////////////////////////////////=//
//
// There are a finite number of builtin datatypes (up to 60 HeartEnum values)
//
// So extension types all use the same heart value of 0.  This means that the
// actual extension type's information is stored in the Cell's "extra" slot.
//
// The choice of 0 is purposeful.  It means that Type can be tested for
// quickly in an if() statement to see if the type is not built in, and it
// can work with the Option() wrapper in the C++ build to do systemic type
// checking that differentiates places that haven't checked if the type is
// built in or not.
//
// 1. The enum value is called TYPE_0_constexpr, because TYPE_0 adds the extra
//    safety of the Option().  This is good because it helps stop people from
//    passing the raw TYPE_0 to functions taking Heart and not Option(Heart).
//    But in case labels of switch() you can't use a class like Option(), so
//    TYPE_0_constexpr must be used instead.
//
// 2. Disabling comparison of Option(Heart) and Option(Type) with each other
//    helps avoid the false positives of extension types comparing as equal:
//
//        if (Type_Of(cell) == Type_Of(other_cell)) { ... }
//
//    The problem is that all extension types are TYPE_0, so they all would
//    compare equal if this were allowed.  Thankfully the C++ build lets
//    us catch this case at compile time.
//

#if (! NEEDFUL_OPTION_USES_WRAPPER)
    #define HEART_0  HEART_0_constexpr  // [1]
    #define TYPE_0  TYPE_0_constexpr
#else
    #define HEART_0  u_cast(Option(Heart), HEART_0_constexpr)  // [1]
    #define TYPE_0  u_cast(Option(Type), TYPE_0_constexpr)

    ENABLE_IF_EXACT_ARG_TYPE(Option(Type))
    void operator==(const T&, const T&) = delete;  // [2]

    ENABLE_IF_EXACT_ARG_TYPE(Option(Type))
    void operator!=(const T&, const T&) = delete;

    ENABLE_IF_EXACT_ARG_TYPE(Option(Heart))
    void operator==(const T&, const T&) = delete;

    ENABLE_IF_EXACT_ARG_TYPE(Option(Heart))
    void operator!=(const T&, const T&) = delete;
#endif


//=//// SINGLEHEART OPTIMIZED SEQUENCE TYPE ///////////////////////////////=//
//
// In Ren-C, `/foo` is a 2-element PATH! with a BLANK! at the head, and `bar:`
// is a 2-element CHAIN! with a BLANK! at the tail.  Due to how common these
// are, and the fact that they are immutable sequences, there is investment
// in optimizing them.  They are called "SingleHeart" sequences, and because
// detection of these is so common there's a special enum which multiplexes
// both the Heart and whether there is a blank at the head or tail.
//
// (It's encoded in a single enum, because if the leading blank or trailing
// blank were separated from the heart type, you could accidentally check
// the leading blank or trailing blank without verifying a sequence was a
// single hearted type.  Static analysis caught bugs of that kind, and they
// are easy to make.)
//
// (See notes on SingleHeart definition for more...)

INLINE bool Singleheart_Has_Trailing_Blank(SingleHeart single) {
    assert(single != NOT_SINGLEHEART_0);
    return did (i_cast(uint_fast16_t, single) & 0xFF);
}

#define Singleheart_Has_Leading_Blank(single) \
    (not Singleheart_Has_Trailing_Blank(single))

INLINE Heart Heart_Of_Singleheart(SingleHeart single) {
    assert(single != NOT_SINGLEHEART_0);

    Heart heart;
    if (Singleheart_Has_Trailing_Blank(single))
        heart = i_cast(Heart, i_cast(uintptr_t, single) << 16);
    else
        heart = i_cast(Heart, i_cast(uintptr_t, single) << 8);

    assert(heart != HEART_0_constexpr and heart != HEART_BLANK);
    return heart;
}
